"""New Migration

Revision ID: a5383190faa2
Revises: 7ae7d0980f1f
Create Date: 2022-06-29 13:47:47.335861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5383190faa2'
down_revision = '7ae7d0980f1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
